url: "https://mochimilk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/hulu-showtiles" # the subpath of your site, e.g. /blog
title: "Hulu Sandbox" # the name of your site, e.g. ACME Corp.

